information_retriever: !RankingRetriever
  database: openbookqa
  k: 1
prompt_template: !PromptTemplate
  template: assets/prompting_templates/openbookqa/3_shot_1_documents.txt
language_model: !BLOOM176bAPI