information_retriever: !VectorRetriever
  database: openbookqa
  k: 1
prompt_template: !PromptTemplate
  template: assets/prompting_templates/openbookqa/4_shot_1_documents.txt
language_model: !BLOOM176bAPI