information_retriever: !VectorRetriever
  database: openbookqa
  k: 1
prompt_template: !PromptTemplate
  template: assets/prompting_templates/openbookqa/permutations/permutation_6.txt
language_model: !BLOOM176bAPI