import cohere
from cohere import CohereError

from piqard.language_models.language_model import LanguageModel
from piqard.utils.exceptions import LanguageModelAPIBlockedOutput
from piqard.utils.io import get_env_variable


class CohereAPI(LanguageModel):
    """
    Wrapper around Cohere language model API.

    To use, you should have the environment variable ``COHERE_API_KEY`` set with your API key
    """

    def __init__(
        self,
        stop_token: str = None,
        max_tokens: int = 50,
        temperature: float = 0,
        top_k: int = 1,
    ):
        """
        Constructor for the Cohere API wrapper.

        :param stop_token: The token that indicates the end of the answer.
        :param max_tokens: The maximum number of tokens to generate.
        :param temperature: The temperature of the language model.
        :param top_k: Number of most likely tokens to consider for generation at each step.
        """
        super().__init__(stop_token)
        self.API_KEY = get_env_variable("COHERE_API_KEY")
        self.client = cohere.Client(self.API_KEY)
        self.parameters = {
            "model": "xlarge",
            "truncate": "START",
            "max_tokens": max_tokens,
            "temperature": temperature,
            "k": top_k,
        }

    def query(self, payload: str) -> str:
        """
        Gather the partial answers from the language model and return the full answer.

        :param payload: The payload to query the language model with.
        :return: The answer generated by the language model.
        """
        generated_answer = self.single_query(payload)
        requests_number = 1
        if self.stop_token:
            while generated_answer.find(self.stop_token) == -1 and requests_number < 5:
                requests_number += 1
                generated_text = self.single_query(payload + generated_answer)
                generated_answer += generated_text

        if self.stop_token is None or generated_answer.find(self.stop_token) == -1:
            return generated_answer
        return generated_answer.split(self.stop_token)[0]

    def single_query(self, payload: str) -> str:
        """
        Queries the language model with the given payload.

        :param payload: The payload to query the language model with.
        :return: The answer generated by the language model.
        """
        try:
            response = self.client.generate(prompt=payload, **self.parameters)
            return response.generations[0].text.strip().strip("\n")
        except CohereError as e:
            if e.http_status == 598:
                raise LanguageModelAPIBlockedOutput(self.__str__())
            else:
                raise e

    def __str__(self) -> str:
        return "Cohere API"
