from piqard.utils.yaml_constructor import yaml_constructor


@yaml_constructor
class LanguageModel:
    """
    LanguageModel is an abstract class that represents a language model.
    """

    def __init__(self, stop_token: str = None):
        """
        Constructor for the LanguageModel class.

        :param stop_token: The token that indicates the end of the answer.
        """
        self.stop_token = stop_token

    def query(self, payload: str) -> str:
        """
        Queries the language model with the given payload.

        :param payload: The payload to query the language model with.
        :return: The answer generated by the language model.
        """
        pass

    def __str__(self) -> str:
        return self.__class__.__name__
