information_retriever: !VectorRetriever
  database: openbookqa
  k: 3
prompt_template: !PromptTemplate
  template: assets/prompting_templates/openbookqa/5_shot_3_documents.txt
language_model: !BLOOM176bAPI