information_retriever: !VectorRetriever
  database: openbookqa
  k: 3
  n: 5
prompt_template: !PromptTemplate
  template: assets/prompting_templates/openbookqa/dynamic_prompt.txt
language_model: !BLOOM176bAPI