piqard: !PIQARD
#  information_retriever:
#    database:
  large_language_model: !BLOOM176bAPI
  prompt_template: prompting/templates/context_prompt.txt
  context_builder: !TruncatedContextBuilder
result_dir: result
