prompt_template: !PromptTemplate
  template: assets/prompting_templates/openbookqa/chain_of_thought/cot_5_shot.txt
  fix_text: "So the final answer is:"
language_model: !BLOOM176bAPI
  stop_token: "|||"