information_retriever: !VectorRetriever
  database: openbookqa
  k: 1
prompt_template: !PromptTemplate
  template: assets/prompting_templates/openbookqa/5_shot_1_documents.txt
language_model: !BLOOM176bAPI
  stop_token: "\n"