prompt_template: !PromptTemplate
  template: assets/prompting_templates/self_aware/self_aware_prompt.txt
language_model: !CohereAPI
  stop_token: "\n"
  temperature: 0
  top_k: 1
if_should_browse: !PIQARD
  prompt_template: !PromptTemplate
    template: assets/prompting_templates/like_chat_gpt/with_context.txt
  language_model: !CohereAPI
    stop_token: "\n"
  information_retriever: !WikiAPI
    k: 10
if_should_not_browse: !PIQARD
  prompt_template: !PromptTemplate
    template: assets/prompting_templates/like_chat_gpt/without_context.txt
  language_model: !CohereAPI
    stop_token: "\n"