information_retriever: !RankingRetriever
  database: openbookqa
prompt_template: assets/prompting_templates/openbookqa/5_shot.txt
context_builder: !TruncatedContextBuilder
language_model: !BLOOM176bAPI